

# mysql database connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boilerplate
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
# server port
server:
  port: 8081
